### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Surfingnet** [gcamerli/42norme#1]
<img width="1280" alt="Capture d’écran 2020-05-28 à 07 58 01" src="https://user-images.githubusercontent.com/10564571/83104479-1df1c800-a0b9-11ea-9e31-3c32e148fd8c.png">

**Comment by gcamerli** [comment]
hey, the repo is not maintained anymore since a while :D Feel free to fork it or to send a pr :dolphin:

**Comment by gcamerli** [comment]
I close the issue as you can find [here](https://github.com/42Paris/norminette) a more updated version in ruby, officially maintained by @42Paris It can be also a worthy exercise to recode on your own picking a language of your choice.
